<?xml version="1.0" encoding="UTF-8"?>
<!-- @deprecated This file will be removed in later release. Users should migrate to "ANSI.sublime-syntax" asap. -->
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>ANSI</string>
  <key>scopeName</key>
  <string>text.ansi</string>
  <key>patterns</key>
  <array></array>
</dict>
</plist>
